#!/usr/bin/env python3
"""One-off generator for large JSON corpora. Run from repo root: python tools/gen_story_data.py"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def w(exp, weight=1):
    return {"expansion": exp if isinstance(exp, list) else [exp], "weight": weight}


def write_json(name, obj):
    path = os.path.join(ROOT, name)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)
    print("wrote", path)


def gen_events():
    stems = [
        "they listened to a story that changed with every retelling",
        "they traded a secret for safe passage across a guarded canal",
        "they stared into a mirror that showed a different face",
        "they climbed a crumbling stair that counted their regrets",
        "they repaired a sail while lightning wrote promises in the sky",
        "they followed a trail of wax drops into a shuttered chapel",
        "they deciphered a map drawn in a language of smells",
        "they paid a toll with a memory they pretended not to miss",
        "they woke in a room where all the doors had swapped walls",
        "they forged a signature that belonged to no living hand",
        "they questioned a child who spoke in the voice of the storm",
        "they hid inside a funeral crowd and learned a name",
        "they drank tea steeped with herbs that made truth taste sweet",
        "they crossed a battlefield picking up unbroken buttons",
        "they rang a bell that answered in a distant city",
        "they planted iron nails at a crossroads to bind a promise",
        "they read a letter meant for someone who shared their shadow",
        "they swam a flooded tunnel by touch alone",
        "they bargained with a river spirit using riddles as coin",
        "they learned a dance step that opened a hidden hatch",
        "they burned a coat because it still smelled like fear",
        "they traced graffiti that predicted the next three days",
        "they scaled a library shelf like a cliff of paper",
        "they copied a constellation onto the deck of a ship",
        "they taught a bird a whistle that warned of betrayal",
        "they stitched a wound with thread taken from a wedding veil",
        "they opened a lock with a key carved from ice",
        "they followed a dog that refused to be petted",
        "they rowed through mist until the oars caught starlight",
        "they wrote a will that disinherited their old self",
        "they camped inside a giant ribcage and listened to the wind",
        "they pressed a silver coin into the palm of a sleepwalker",
        "they tasted honey that recalled a childhood they never lived",
        "they translated thunder into marching orders",
        "they cut their hair as a signal only insiders understood",
        "they measured footsteps to prove the house was growing",
        "they lit a candle that burned in two directions at once",
        "they stole back their own reflection from a mountebank",
        "they helped a stranger bury a crate marked with their initials",
        "they chased a echo until it grew tired and turned honest",
        "they learned which wells echoed with answers instead of drips",
        "they folded a map until it became a blade",
        "they braided ribbons into a rope strong enough for lies",
        "they sharpened a pen until it could cut through testimony",
        "they painted a door where a wall insisted there was none",
        "they accepted a gift wrapped in warnings",
        "they scraped mold from bread and called it strategy",
        "they counted heartbeats to time the patrols",
        "they lowered a lantern into a well and pulled up singing",
        "they traded boots with a pilgrim to confuse pursuit",
        "they carved a name into bark that healed overnight",
        "they caught rain in a sieve and called it patience",
        "they watched a puppet show where the strings argued back",
        "they rescued a cat that refused to leave the burning house",
        "they memorized a hymn backwards to unsettle a zealot",
        "they sang lullabies to calm a weapon that dreamt",
        "they replaced a king's portrait with a window",
        "they learned to breathe in rhythm with the city's machines",
        "they traced a vein of quartz that pulsed like a vein",
        "they followed bloodspots that climbed upward against gravity",
        "they opened an umbrella beneath a ceiling of falling knives",
        "they fed soup to a fever until it broke like dawn",
        "they copied a guard's yawn until they mirrored his shift",
        "they stitched a flag from enemy banners and flew anew",
        "they taught a storm to wait at the threshold politely",
        "they walked backwards through market day and learned who watched",
        "they caught snow on their tongue and named the winter",
        "they braided someone's hair to hide a micro-message",
        "they learned the local slang for danger and for mercy",
        "they pressed their ear to rails and heard tomorrow's train",
        "they buried shame beside a sapling to see which grew faster",
        "they rode a raft through a canyon of whispering stone",
        "they sharpened chalk and left marks only moonlight revealed",
        "they caught a lie mid-air and folded it into a crane",
        "they traded coats so the rain would misunderstand who fled",
        "they practiced silence until it became a shield",
        "they traced a spiral in ash that made the room listen",
        "they opened a book where every margin argued",
        "they pretended to lose a duel to learn the victor's route",
        "they braided reeds into a whistle only the lost could hear",
        "they found a staircase that appeared only while yawning",
        "they followed a river upstream until language thickened",
        "they burned a diary and read the smoke",
        "they helped a clock run slow enough to forgive",
        "they cut a path through a hedge that rearranged behind them",
        "they learned which windows were polite to knock on",
        "they caught a feather that weighed more than steel",
        "they listened to coins and knew which were cursed",
        "they painted a wound with iodine and honesty",
        "they learned a joke that could stop a spear mid-throw",
        "they followed footprints that stepped lighter than truth",
        "they opened a gate by apologizing to the hinges",
        "they taught a river new words by throwing polished stones",
        "they braided candle wicks into a fuse for patience",
        "they traced a sigil with a finger dipped in storm water",
        "they swapped shoes at a shrine to confuse fate",
        "they copied a nightmare and filed it as evidence",
        "they watched moss decide which wall would win",
        "they measured rope by how far regret could stretch",
        "they followed a thread through a tapestry of wars",
        "they caught smoke in a jar and debated releasing it",
        "they learned to nod in a way that meant both yes and wait",
        "they sharpened their courtesy until it cut cleaner than steel",
        "they fed a stray dog and inherited its enemies",
        "they opened a seam in reality with a tired shrug",
        "they followed the smell of ink to a forbidden archive",
        "they learned which bridges demanded a toll of laughter",
        "they stitched pockets into the sky to hold spare seconds",
        "they listened to a shell and heard not the sea but orders",
        "they traded names at a border until maps grew confused",
        "they braided garlic into a wreath against softer curses",
        "they sharpened their listening until silence spoke last",
        "they followed a trail of bread that led to a hungry truth",
        "they opened an envelope sealed with someone else's pulse",
        "they taught a shadow to walk beside them politely",
        "they carved a flute from bone and played a truce",
        "they walked a tightrope of promises stretched between towers",
        "they painted a doorway with light saved from yesterday",
        "they followed the tide's advice and arrived between hours",
        "they learned which stars were satellites pretending",
        "they caught a rumor and vaccinated it with context",
        "they braided nettles into gloves for shaking traitors' hands",
        "they traced a spiral on water until it remembered being ice",
        "they swapped cloaks with a statue to learn stillness",
        "they opened a grave to ask a question and closed it gently",
        "they followed a fox that waited for permission at every fence",
        "they learned which candles burned best for difficult truths",
        "they measured a room by how many apologies fit inside",
        "they stitched a sail from apologies and caught a fierce wind",
        "they followed thunder home until it admitted it was tired",
        "they opened a piano and found letters instead of strings",
        "they braided rumors until one snapped into a fact",
        "they sharpened dawn until it could slice through fog",
        "they walked backwards through their mistakes without tripping",
        "they caught a moth carrying powder that revealed hidden ink",
        "they learned to knock in a rhythm that opened secret wards",
        "they traded riddles with a door until it surrendered",
        "they painted waves on dry stone until the stone listened",
        "they followed grief until it led them back to breath",
        "they opened a cage and discovered the lock was ornamental",
        "they braided wind into a net for catching stray oaths",
        "they learned which songs made guards forget their orders",
        "they measured distance in stories, not miles",
        "they stitched a compass from broken needlepoints",
        "they followed a river of spilled wine to a treaty table",
        "they opened a vein of old magic with a careful apology",
        "they braided fear into rope and climbed out of a well",
        "they learned which mirrors were polite enough to lie",
        "they counted blessings until math became mercy",
        "they traded a scar for directions only pain could read",
        "they followed laughter until it stopped pretending to be joy",
        "they opened an attic of weather and borrowed a gentle rain",
        "they braided salt into thread for sewing wounds shut",
        "they learned which herbs turned panic into planning",
        "they measured courage by how gently they closed a door",
        "they stitched the horizon back onto the sea after a storm",
        "they followed footprints out of a story and into a choice",
        "they opened a chest labeled 'winter' and found spring",
        "they braided lightning into a necklace nobody could wear twice",
        "they learned which windows looked inward instead of out",
        "they traded silence for shelter under a loud roof",
        "they followed a map written on the inside of their eyelids",
        "they opened a bottle and released a draft of old courage",
        "they braided vows into a belt strong enough to hold a city",
        "they learned which hands to shake and which to heal",
        "they measured time by how much moonlight pooled in a cup",
        "they stitched night into a cloak for crossing bright places",
        "they followed echoes until one introduced itself as memory",
        "they opened a wound into a window and saw the road ahead",
        "they braided dawn into their hair to greet suspicious guards",
        "they learned which doors opened to honesty whispered",
        "they traded a crown of thorns for a crown of questions",
        "they followed a pilgrimage of ants toward sweeter wreckage",
        "they opened a letter written by the road itself",
        "they braided starlight into gauze for dressing fierce hope",
        "they learned which valleys hoarded voices like coins",
        "they measured loyalty by who stayed after the story ended",
        "they stitched lies into a quilt warm enough to survive winter",
        "they followed fireflies arranging constellations on a marsh",
        "they opened a music box and found footsteps instead of tune",
    ]
    extra = []
    verbs = [
        "crossed",
        "descended",
        "ascended",
        "raced",
        "crept",
        "sprinted",
        "tumbled",
        "sidled",
        "inched",
        "vaulted",
        "waded",
        "limped",
        "marched",
        "cantered",
        "ferried",
        "ferreted",
        "pressed",
    ]
    places = [
        "a canyon of numbered bones",
        "a market that only opened at midnight",
        "a shrine built from shipwreck timber",
        "a bridge repainted overnight",
        "a graveyard of musical instruments",
        "a greenhouse of glass teeth",
        "a courthouse run by birds",
        "a mine that sang when struck",
        "a bathhouse where steam showed futures",
        "a canyon netted with prayer flags",
        "a district zoned for miracles",
        "a station where trains exchanged secrets",
        "a cliff face carved with apologies",
        "a cellar lined with bottled laughter",
        "a pier where fish returned letters",
        "a ward guarded by courteous ghosts",
        "a forum where silence was currency",
        "a observatory aimed inward",
        "a orchard where fruit ripened backwards",
        "a fort built from borrowed minutes",
    ]
    objs = [
        "an oar snapped clean across a lie",
        "a ribbon tied to a weapon hilt",
        "a compass that pointed to hunger",
        "a torch that burned with cold",
        "a whistle carved from courthouse oak",
        "a seal broken by breath alone",
        "a mask warm enough to weep under",
        "a chain of names too long to carry",
        "a horn that called rain instead of war",
        "a ring that fit every finger but one",
        "a bottle labeled with a child's drawing",
        "a harp strung with shoelaces and vows",
        "a cloak lined with pocketed dusk",
        "a dagger wrapped in wedding rice",
        "a book whose index page bled",
    ]
    import random

    random.seed(42)
    while len(stems) < 220:
        v = random.choice(verbs)
        p = random.choice(places)
        o = random.choice(objs)
        stems.append(f"they {v} through {p} carrying {o}")
    seen = set()
    out = []
    for s in stems:
        t = s.strip()
        if t not in seen:
            seen.add(t)
            out.append(t)
    while len(out) < 220:
        out.append(f"they chose a path the map called '{len(out)} thorns wide'")
    return out[:220]


def gen_lines(prefix_style, n, base_phrases, more=None):
    lines = list(base_phrases)
    if more:
        lines.extend(more)
    while len(lines) < n:
        lines.append(lines[len(lines) % len(base_phrases)] + f" ({len(lines)})")
    return [w(x) for x in lines[:n]]


def main():
    write_json("events.json", gen_events())

    atm = [
        "The air was thick with tension.",
        "A cold wind blew, carrying the scent of rain and rust.",
        "The world held its breath, as if listening for a name.",
        "Distant thunder rolled like a borrowed drum.",
        "Fog threaded between the trees and swallowed small sounds.",
        "Lantern light trembled on wet cobblestones.",
        "The silence was not peace; it was waiting dressed as calm.",
        "Heat shimmered above the road in restless, guilty waves.",
        "Stars sharpened until the sky felt close enough to cut palms.",
        "The hour felt suspended between yesterday and a sharper tomorrow.",
        "Birdsong cut off all at once, unnaturally still.",
        "Ash drifted like slow snow from a sky the color of iron.",
        "The market noise faded until only heartbeats argued.",
        "Salt stung the air, sharp and bracing as truth.",
        "A bell tolled once, and every face turned toward it.",
        "The forest smelled of pine resin and older, wetter secrets.",
        "Candle smoke curled like handwriting no one could read yet.",
        "A dog barked once, listened, and refused a second time.",
        "The river ran higher, carrying voices downstream.",
        "Clouds stacked like ledgers full of unpaid oaths.",
        "The heat of the forge kissed the street through open doors.",
        "Someone swept glass in the distance, a crisp, nervous rhythm.",
        "The moon looked smaller, as if the night had flinched.",
        "A choir practiced a hymn that kept changing key.",
        "The palace shutters rattled though no hand touched them.",
        "Snow hesitated midway, as if asking permission to fall.",
        "The harbor smelled of tar, oranges, and unwashed luck.",
        "The wind carried chimney smoke in a straight, deliberate line.",
        "Footprints crossed each other until the road looked argued over.",
        "The orchard smelled like bruised apples and patience.",
        "The cathedral drafts played a single long note endlessly.",
        "A cartwheel squealed like an animal refusing work.",
        "The desert air tasted of metal and swallowed echoes.",
        "Lightning wrote a crooked signature everyone pretended not to see.",
        "The tavern went quiet when the stranger counted coins slowly.",
        "Ice crackled on the eaves like whispered warnings.",
        "The meadow grass lay flat as if pressed by an invisible palm.",
        "The tavern clock refused twelve and lingered on eleven.",
        "Rain drummed on canvas awnings like impatient fingers.",
        "The mountain pass exhaled a breath cold enough to cut skin.",
        "A bell rope frayed thread by thread in the humid air.",
        "The city smelled of fried onions, ink, and something burning.",
        "A fountain ran, but the water looked too clear to trust.",
        "The battlefield smelled like wet iron and used-up courage.",
        "Paper curled in the heat, edges lifting like startled birds.",
        "A child laughed once, high and bright, and adults flinched.",
        "Smoke hung low, as if ashamed to rise.",
        "The stairwell smelled of beeswax and someone else's worry.",
        "The horizon jittered faintly, a heat trick or a promise.",
        "Horses shifted in the stable, coats dark with nervous sweat.",
        "The lane narrowed until two honest people could not pass unchanged.",
        "Glass windows reflected torches twice, as if time had a twin.",
        "A door stuck, then gave, exhaling a breath of cold cellar air.",
        "The prison corridor smelled of lye, bread, and tired stone.",
        "The marsh bubbled softly, polite about its hunger.",
        "The valley wind carried needle-pine and distant drums.",
        "Someone tuned a fiddle badly, on purpose, as a warning.",
        "The arena sand had been raked into impossible straight lines.",
        "The orchard gate hung crooked, inviting trouble politely.",
        "The harbor bell rang sour, as if embarrassed by its job.",
        "The cliff face sweated dew though the sun had not risen.",
        "The abbey cloister smelled of thyme and quietly held breaths.",
        "A bridge rope thrummed with tension and distant footsteps.",
        "The workshop smelled of ozone, oil, and stubborn hope.",
        "Sand hissed against shutters like impatient parchment.",
        "A hawk circled once, declined a second pass, and left.",
        "The throne room candles burned blue at the very edge of wicks.",
        "Rain tasted clean until lightning made the air taste copper.",
        "The lane lamps flickered in sequence, spelling nothing kind.",
        "The river mud released bubbles like slow, buried speech.",
        "The stair smelled of iron polish and someone's polished fear.",
        "A fiddle bow scraped silence until silence answered back.",
        "The courtyard well rope coiled like something pretending sleep.",
        "The morning mist hid teeth; the afternoon would prove it.",
        "A gateward coughed; the echo traveled farther than politeness.",
        "The cliff path felt narrower once you noticed the drop.",
        "The bakery oven coughed heat into a street already nervous.",
        "The graveyard path softened, as if the ground remembered knees.",
        "A shutter flapped a rhythm out of step with the wind.",
        "The ship's rigging sang a thin, skeptical song.",
        "The canyon breathed out warmth it had stolen all morning.",
        "The tunnel mouth exhaled a draft that tasted of libraries.",
        "The fairground lights buzzed, hungry for dusk.",
        "The courtyard fountain coughed once, then pretended innocence.",
        "Smoke painted the sunset with colors the sermon had forbidden.",
        "The ridge wind tugged at cloaks like impatient hands.",
        "The harbor cleat gleamed where a thousand ropes had worried it.",
        "The barn smelled of hay, old blood, and new decisions.",
    ]
    write_json("atmosphere.json", [w(s) for s in atm[:90]])

    th = [
        "They wondered if it would ever end, and what ending could mean.",
        "They asked themselves what price they were willing to pay for one more dawn.",
        "They thought of home, and whether it still existed in any honest sense.",
        "They questioned every kindness, searching for a hook buried in sugar.",
        "They replayed old failures until their jaw ached from clenching.",
        "They imagined another life, softer, smaller, and cruel in its comfort.",
        "They tried not to think of the worst, and failed with impressive thoroughness.",
        "They counted breaths until their pulse slowed into something usable.",
        "They felt time bend, cruel and intimate as a held hand.",
        "They wondered who they would be when this was over—if anyone would be.",
        "They measured courage against exhaustion and found both stubbornly present.",
        "They wished for a sign, then feared receiving one too clearly.",
        "They remembered a promise and tightened their grip on it until it hurt.",
        "They suspected the truth was worse than the lie everyone preferred.",
        "They felt watched by something older than the road and less impressed.",
        "They told themselves fear was only information, then listened poorly anyway.",
        "They wondered if mercy would be mistaken for weakness by wolves.",
        "They rehearsed apologies they might never get to trade.",
        "They considered running, then named the reasons running would follow them.",
        "They felt gratitude arrive uninvited, inconvenient, undeniable.",
        "They asked the night a question and pretended the echo was an answer.",
        "They wondered if love was a luxury their mission could survive.",
        "They tried to inventory their regrets and ran out of paper.",
        "They told themselves stories to stay human, even if stories lied.",
        "They suspected their hands had learned violence too easily.",
        "They wondered what forgiveness would cost the people wronged least.",
        "They traced their scars like a map of classrooms they never chose.",
        "They feared becoming the thing they were hunting.",
        "They hoped, cautiously, like someone testing a frozen lake.",
        "They weighed duty on one palm and love on the other; neither balanced.",
        "They recalled a lullaby and felt dangerously young again.",
        "They asked whether salvation could arrive dressed as defeat.",
        "They listened for their old name and barely recognized its sound.",
        "They wondered if the gods were listening or merely taking notes.",
        "They tried to feel nothing, and felt everything sharpen.",
        "They considered how many lies a good outcome can excuse.",
        "They thought about bread, suddenly, and missed it like a country.",
        "They wondered if they were the hero or the lesson.",
        "They questioned every map, especially the one in their chest.",
        "They imagined the aftermath and flinched from its empty rooms.",
        "They hoped their courage would not be quoted out of context later.",
        "They asked the storm politely, inside themselves, to wait.",
        "They wondered if grief was a river or a weapon you polished.",
        "They tried to remember who benefited from their silence.",
        "They suspected laughter had become a currency they were short on.",
        "They asked if redemption required witnesses or only witnesses' absence.",
        "They wondered whether trust could be repaired like pottery.",
        "They thought of the last safe door and how quickly 'safe' ages.",
        "They questioned their memory, the sneakiest storyteller of all.",
        "They imagined future children judging them with clear, brutal eyes.",
        "They wondered if patience was bravery slowed down.",
        "They tried to name the feeling between dread and determination.",
        "They asked whether hope was discipline wearing a softer mask.",
        "They considered how much truth a friendship can survive at once.",
        "They wondered if the road was teaching them or using them.",
        "They thought about sleep as if it were a distant relative.",
        "They questioned the kindness of strangers and still accepted water.",
        "They tried to rehearse grief and found it refused rehearsal.",
        "They wondered if every crown began as a circle of thorns negotiated.",
        "They asked themselves what they would trade for one honest mirror.",
        "They thought about rivers, and how they never apologize for carving.",
        "They suspected their courage was made from borrowed minutes.",
        "They wondered if the villain had once asked the same questions.",
        "They tried to decide whether doubt was wisdom or exhaustion.",
        "They asked if love could be proven without someone paying for the proof.",
        "They thought of music and felt dangerously close to tears.",
        "They wondered whether peace was a place or a practice.",
        "They questioned their hunger for vengeance like a doctor palpating.",
        "They tried to imagine a quiet life and failed beautifully.",
        "They asked if sacrifice stops hurting once you name it noble.",
        "They wondered how many apologies a city can drink before drowning.",
        "They thought about fire, and how it pretends to be honest.",
        "They suspected they were being softened for a harder lesson.",
        "They asked the stars for privacy; the stars offered distance.",
        "They wondered if courage always looked like shaking hands.",
        "They tried to inventory their loves and found the list unclosable.",
        "They asked whether mercy could be strategic without becoming cruel.",
        "They thought about scars as a language written without consent.",
        "They wondered if tomorrow would forgive them for surviving today.",
        "They questioned the story they had been told about themselves.",
        "They tried to pray without bargaining; it felt like learning to swim.",
        "They asked if endings were kinder when shared.",
        "They wondered whether truth could arrive too early and spoil.",
        "They thought about coins, crossings, and how both demand choices.",
        "They suspected joy had gone into hiding until the work finished.",
        "They asked whether loyalty could survive being tested twice.",
        "They wondered if every blessing arrived with a shadow subscription.",
        "They tried to feel the boundary between instinct and prejudice.",
        "They asked if home was a person, a place, or a permission.",
        "They thought about water, and how it always finds the lowest truth.",
        "They wondered whether they could carry this and still grow gentle.",
        "They questioned the clock: ally, witness, or accomplice.",
        "They tried to remember the last time they felt unwatched.",
        "They asked whether forgiveness required forgetting or facing.",
        "They wondered if their name sounded different in someone else's mouth.",
        "They thought about bridges, and how walking them changes both shores.",
    ]
    write_json("thoughts.json", [w(s) for s in th[:90]])

    tr = [
        "Later that day,",
        "The next morning,",
        "When the sun dipped low,",
        "As night tightened its grip,",
        "After hours of careful planning,",
        "By midday, the road had changed them again,",
        "In the hush between heartbeats,",
        "When the bells rang out across the valley,",
        "After a brief rest that felt like stolen time,",
        "As the tide turned and the harbor stirred,",
        "When the storm finally broke,",
        "Under a sky bruised with color,",
        "Once the crowd thinned and footsteps faded,",
        "When the candles burned down to stubborn nubs,",
        "As the first snow hesitated on the ridge,",
        "After a meal that tasted like a truce,",
        "While the guards changed shift and clocks argued,",
        "When the forest opened into a clearing nobody mapped,",
        "As the city gates sighed shut for curfew,",
        "When the river rose to swallow the stepping stones,",
        "After a messenger arrived breathless and word-heavy,",
        "While thunder cleared its throat over the mountains,",
        "When the market bells announced both bread and bad news,",
        "As dawn peeled the night back like bark,",
        "After the ink dried on a document nobody wanted to sign,",
        "When hoofbeats slowed to a respectful walk,",
        "As fog lifted from fields stitched with footprints,",
        "When the cathedral choir paused between verses,",
        "After laughter peeled through a hall like thin ice breaking,",
        "While a distant hammer and anvil argued in rhythm,",
        "When the watch changed and lanterns swapped hands,",
        "As the tide revealed a path that wasn't there at noon,",
        "After a child pointed at something adults pretended not to see,",
        "When the rain paused, polite as a held breath,",
        "As the banquet ended and knives were counted,",
        "When the horizon swallowed the last friendly color,",
        "After signatures hardened wax into brittle proof,",
        "While bees returned late to hives heavy with rumor,",
        "When the map tore along a fold it had been hiding,",
        "As the wind turned and carried a stranger's perfume,",
        "After the oath left their mouth and could not be cupped back,",
        "When drums began somewhere beyond the nearest hill,",
        "As a bell rope broke and silence took its shift,",
        "When the ship's lantern started swinging like a pendulum,",
        "After they counted coins and found morality expensive,",
        "While the orchard released apples into bruising gravity,",
        "When the courtroom doors opened on yesterday's weather,",
        "As moonlight stepped through a window it hadn't paid for,",
        "After the wound stopped pretending to be small,",
        "When the parade turned a corner into narrower destiny,",
        "As the fountain resumed speaking after being silenced,",
        "When boots found purchase on ice that promised nothing,",
        "After a hinge screamed and a secret became inevitable,",
        "While smoke wrote its slow handwriting across the valley,",
        "When the desert night dropped its temperature like a verdict,",
        "As the lighthouse beam discovered them, willing or not,",
        "After a vow exchanged hands heavier than steel,",
        "When the echo finally caught up with the shout,",
        "As morning light made every lie look well-rested,",
        "After the theater crowd thinned to the stubborn and the lost,",
        "When the pilgrimage path narrowed between two honest stones,",
        "As soup cooled into a broth of practical decisions,",
        "When the watchtower flag tied itself into a nervous knot,",
        "After the manuscript shed a page like a deciduous guilt,",
        "While gulls argued over a harbor full of borrowed time,",
        "When the ridge offered wind enough to peel cowardice away,",
        "As the spire's shadow clocked their choices like sundial teeth,",
        "After the bridge planks tested their weight with honest creaks,",
        "When lanterns were lowered, signaling a darker kind of business,",
        "As dust settled on every promise left out in the open,",
        "After the lullaby ended and the nursery listened harder,",
        "When the tide brought in splinters shaped like old crowns,",
        "As the council room emptied, leaving politics on the table,",
        "After a door marked 'private' sighed open anyway,",
        "While the mural's eyes followed them with indecent attention,",
        "When the city exhaled smoke the color of borrowed dawn,",
        "As boots crossed a threshold painted with warnings in chalk,",
        "After the trial's last word hung like smoke in winter air,",
        "When bells disagreed across two districts about the hour,",
        "As the river ferry bumped the dock like a blunt confession,",
        "After heat lightning sketched futures nobody asked to see,",
        "While the archive's dust tasted like postponed consequences,",
        "When the road offered three forks and no polite advice,",
        "As the fortress gate teeth closed with a reluctant finality,",
        "After the tavern song changed key and allegiances followed,",
        "When the meadow mist thickened into a soft wall,",
        "As the market cleared, leaving gossip like spilled grain,",
        "After the mirror steamed and wrote a name backward,",
        "While distant wolves rehearsed harmonies the moon ignored,",
        "When the pilgrimage bell rang thin, as if embarrassed,",
        "As sand erased footprints with the patience of judges,",
        "After the treaty ink smeared under a saluting palm,",
        "When lightning paused mid-throw, studying its target,",
        "As dawn traded colors with a horizon reluctant to commit,",
    ]
    write_json("transitions.json", [w(s) for s in tr[:90]])

    tw = [
        "the ally had been the architect of the plot all along",
        "the curse and the cure were the same words spoken differently",
        "the enemy had saved them once, for reasons still unknown",
        "the map had been drawn to lead them away, not toward",
        "the victory had been bargained for before they were born",
        "the prophecy had been written as a trap, not a promise",
        "the silence at the end was an answer no one wanted",
        "the treasure was a memory stolen from someone else",
        "the storm had been called by a name they had spoken aloud",
        "the crown fit because it had always been meant for them",
        "the door they opened was never meant to close again",
        "the ghost was not haunting them—it was guiding them",
        "the wound they carried was the key to the final lock",
        "the traitor acted from love, however twisted",
        "the ritual succeeded, but not in the way anyone intended",
        "the city they saved had already chosen a different fate",
        "the song they heard was their own voice, years ahead",
        "the beast was guarding something worse behind it",
        "the bargain was renewed the moment they broke it",
        "the mirror showed a Stranger who recognized them",
        "the final clue had been written in their own handwriting",
        "the peace they won would demand a new war tomorrow",
        "the bell tower had been ringing for someone else's funeral",
        "the river reversed course when the oath left their lips",
        "the portrait aged while the sitter stayed young",
        "the prison door had been left open as an invitation, not mercy",
        "the comet was a message written in a language of removals",
        "the treaty ink could only be read by moonlight",
        "the garden grew only from promises that had been kept",
        "the lighthouse beam pointed inland, not to sea",
        "the coin they carried had been spent twice already",
        "the storm shelter had been built around an old altar",
        "the trial transcript rewrote itself each night",
        "the banner revealed a second emblem when it got wet",
        "the sword remembered hands that were not theirs",
        "the orphan's locket contained sand from a battlefield unbuilt",
        "the mountain pass closed behind them like a satisfied jaw",
        "the bakery fire had been kind to no one but the story",
        "the cathedral vaults hummed with a chord only traitors heard",
        "the refugee ship sailed on water poured from a inkwell",
        "the council seal cracked along a fault line of truth",
        "the horizon line stitched itself tighter when they looked away",
        "the ring warmed when lies approached within ten paces",
        "the watchtower stairs counted down instead of up",
        "the desert well offered wishes on credit",
        "the grave marker bore a date that had not happened yet",
        "the circus tent folded inward until it became a room",
        "the astrolabe tracked hearts instead of heavens",
        "the bridge toll was paid in names, not coin",
        "the harbor chain lifted only for apologies well-phrased",
        "the abbey bell rang only when someone chose mercy coldly",
        "the palace maze rearranged along lines of old grudges",
        "the theater audience had been cast before anyone auditioned",
        "the ransom note used handwriting taught in their childhood",
        "the eclipse arrived early, impatient with schedules",
        "the market scale weighed intentions heavier than goods",
        "the river ferryman's pockets were full of stitches",
        "the throne's cushion hid blades meant for the humble",
        "the prophecy's margins contained instructions in shorthand",
        "the dragon's hoard was mostly letters never sent",
        "the revolution's anthem borrowed a lullaby's bones",
        "the surgeon's kit rattled with instruments for editing fate",
        "the lighthouse keeper kept time by counting heartbeats",
        "the city wall had been mortared with powdered oaths",
        "the astronomer's chart marked futures like wormholes",
        "the trial witness spoke in echoes routed through old wells",
        "the festival mask adhered until the wearer forgot the seam",
        "the soldier's medal warmed whenever someone lied about peace",
        "the orchard gate opened only after a debt was named",
        "the ship's hold carried barrels labeled with living verbs",
        "the canyon echoed negotiations it had overheard for centuries",
        "the mine shafts breathed out drafts of unfinished apologies",
        "the palace cooks seasoned soup with rumors and thyme",
        "the cathedral floor stones shifted to keep pilgrims honest",
        "the river island moved downstream when no one watched",
        "the observatory dome peeled back to reveal a second sky",
        "the battle standard changed colors when guilt approached",
        "the prison chaplain kept keys that opened inward, not out",
        "the mountain hermit's tea leaves spelled out a rebate on fate",
        "the ghost ship's rudder followed regrets, not currents",
        "the duel's adjudicator had already written the footnotes",
        "the coronation crown had been resized by a grieving smith",
        "the marketplace auction sold silences by the hour",
        "the harbor pilot steered by a chart inked in blood-bright dyes",
        "the university seal unlocked doors that led to weather, not rooms",
        "the war drum's skin had been stretched with borrowed patience",
        "the river delta braided itself into a signature",
        "the grave digger's compass pointed toward living rooms",
        "the exile's passport bore stamps from countries of thought",
        "the clock tower struck thirteen only when promises split",
        "the cathedral spire cast a shadow shaped like a question mark",
        "the palace dog barked at empty air that answered in Morse",
        "the treaty table had been carved from a single tree of oaths",
        "the wandering star was a hole punched through night's ledger",
        "the dungeon drip counted time in currencies of endurance",
        "the festival bonfire burned coldest when truth sat close",
        "the hero's epitaph updated itself with every retelling",
        "the final horizon curved like a smile with too many teeth",
    ]
    write_json("twists.json", [w(s.lower()) for s in tw[:90]])

    dg = []
    lines_rot = [
        "Tell me the truth, even if it breaks me,",
        "We still have time,",
        "I choose the next step,",
    ]
    for i in range(70):
        line = lines_rot[i % 3]
        verb = "said" if i % 2 == 0 else "whispered"
        dg.append(w([f' "{line}" they {verb}.']))
    # richer curated snippets mixed
    curated = [
        ' "I will not turn back," they said quietly.',
        ' "Listen," they breathed. "Do you hear that?" ',
        ' "Then we make our own fate," they answered.',
        ' "Not without you," they replied, simple as a blade.',
        ' "What do you want from me?" they asked the silence.',
        ' "Stay close," they murmured. "The path lies." ',
        ' "No more secrets," they said, eyes hard with resolve.',
        ' "Let them come," they said, and stood their ground.',
        ' "I choose mercy," they said, surprising even themselves.',
        ' "I never asked to be chosen," they admitted, bitter and honest.',
        ' "Hold the line," they called to companions they could not see.',
        ' "Forgive me," they said, though no one had asked.',
        ' "I will pay the price," they vowed.',
        ' "Show yourself," they called, hand steady where fear wanted shake.',
        ' "We were warned," they said. "We came anyway." ',
        ' "If I fall, carry the message," they instructed.',
        ' "I don\'t believe in omens," they lied convincingly.',
        ' "Then we do it the hard way," they said, and meant it.',
        ' "The story isn\'t finished," they said, almost smiling.',
        ' "Mercy first," they said, testing the word like a blade\'s balance.',
        ' "Give me one honest reason," they demanded of the dark.',
        ' "I hear you," they answered a voice only they could hear.',
        ' "Anchor me," they asked, smaller than they liked.',
        ' "I am done running," they announced to an empty hall.',
        ' "Say it plain," they asked, exhausted by poetry.',
        ' "We leave at dusk," they said, ending debate.',
        ' "I trust you," they said, and watched what the word cost.',
        ' "Gently," they warned, as if violence could be polite.',
        ' "Again," they said, stubborn as a season.',
        ' "Look up," they whispered. "Don\'t bow to it." ',
        ' "This is not bravery," they said. "It\'s schedule." ',
        ' "Name your fear," they offered, oddly gentle.',
        ' "I remember you," they said to someone they hoped was listening.',
        ' "We eat," they said, restoring civilization by bread.',
        ' "Speak or go," they told the threshold.',
        ' "Not tonight," they said to death, politely.',
    ]
    write_json("dialogues.json", [w(s) for s in curated] + dg[:40])

    emo = [
        " A stubborn hope warmed their chest despite everything.",
        " Fear clawed at them, yet they kept moving.",
        " Grief pressed behind their eyes like a tide held back.",
        " A fierce, unfamiliar pride straightened their shoulders.",
        " Shame flickered and then hardened into resolve.",
        " Wonder broke through weariness like dawn through smoke.",
        " Loneliness settled in their ribs, familiar as an old wound.",
        " Rage burned clean, leaving clarity in its wake.",
        " Doubt whispered, but they refused to answer on its terms.",
        " Relief loosened knots they had carried for days.",
        " A strange calm descended, the kind that follows a decision.",
        " Love—unexpected and inconvenient—caught them off guard.",
        " Exhaustion dragged at their limbs, yet their mind stayed sharp.",
        " Bittersweet gratitude ached in their throat.",
        " They felt small beneath the weight of the moment.",
        " Courage arrived not as bravery, but as refusal to quit.",
        " Regret tasted like metal on their tongue.",
        " They trembled, then steadied, then chose the next step.",
        " Something like faith settled where logic had failed.",
        " They smiled through tears they did not bother to hide.",
        " A cold clarity cut through the noise of their thoughts.",
        " They felt watched, judged, and strangely unalone.",
        " Humility softened their edges without dulling their purpose.",
        " Anticipation thrummed in their veins like a plucked string.",
        " They carried the moment carefully, as if it were glass.",
        " Gratitude hurt, sharp and sweet as winter air.",
        " Disgust rose, then transformed into a tool they could use.",
        " Awe widened them until fear had less room.",
        " Tenderness surprised them more than danger ever had.",
        " Resolve squared their spine where worry had curled it.",
        " Laughter bubbled up, irreverent and lifesaving.",
        " Nostalgia tugged sideways, a tide they refused to swim.",
        " Confusion sharpened into questions worth answering.",
        " Confidence arrived quietly, without brass or boasting.",
        " Vulnerability felt like stepping onto ice that held.",
        " Yearning burned without promising satisfaction.",
        " Peace arrived ugly, practical, and wearable.",
        " Indignation straightened their words into spears.",
        " Weariness became a blanket they refused to hide under.",
        " Curiosity opened doors pride would have kept shut.",
        " Affection ambushed them during an argument.",
        " Suspicion mapped exits before the room finished lying.",
        " Satisfaction felt dangerous, like a gift with strings.",
        " Despair touched them and left, refused service.",
        " Serenity seemed borrowed and they accepted the loan.",
        " Irritation honed their focus into a needle.",
        " Sympathy softened their hands without dulling their aim.",
        " Misgiving paced their ribs like a caged animal.",
        " Boldness tinted the world brighter than lanterns.",
        " Quiet joy threaded through pain like gold in dark cloth.",
        " Protectiveness rose, ancient as fire.",
        " Insecurity hissed; they answered with work.",
        " Longing pressed against their ribs like a second heartbeat.",
        " Shyness peeled away when duty knocked louder.",
        " Euphoria tried to land; they tethered it to facts.",
        " Melancholy sat beside them without asking permission.",
        " Amusement arched an eyebrow at fate's performance.",
        " Respect grew where contempt had been budgeted.",
        " Disappointment settled, then composted into fuel.",
        " Comfort arrived in a stranger's small kindness.",
        " Clarity cut close enough to bleed a little.",
        " Warmth pooled in their hands returning from cold air.",
        " Dread sharpened each sense unbearably, usefully.",
        " Pride loosened its collar and learned to whisper.",
        " Self-protection lowered shields by a breath, on purpose.",
        " Honesty stung their throat raw and felt wholesome.",
        " Compassion rearranged priorities without asking politeness.",
        " Impatience tapped a rhythm they matched to movement.",
        " Patience felt like strength disguised as waiting.",
    ]
    write_json("emotions.json", [w(s) for s in emo[:70]])

    desc = [
        "they had wandered long roads with nothing but stubborn faith.",
        "they had lost much, and learned to carry absence like a tool.",
        "they had been warned by elders, dreams, and common sense alike.",
        "they had survived a winter that taught them how hunger thinks.",
        "they had once believed the world was simpler than it proved to be.",
        "they had made mistakes that still echoed in quiet hours.",
        "they had been chosen, cursed, or merely unlucky—no one agreed which.",
        "they had followed a trail of small lies until it became a road.",
        "they had sworn oaths to people who were gone or changed.",
        "they had learned to read danger in the tilt of a smile.",
        "they had traded comfort for a purpose that refused to let them rest.",
        "they had heard rumors until rumors became a map.",
        "they had trained until their body obeyed before their fear did.",
        "they had kept a secret so long it felt like a second spine.",
        "they had been broken once, and rebuilt with stranger seams.",
        "they had loved someone who taught them the cost of mercy.",
        "they had fled a fire only to discover they carried sparks inside.",
        "they had waited years for a door that finally groaned open.",
        "they had studied old texts until the words began to study them back.",
        "they had crossed borders where names changed and truth thinned.",
        "they had owed debts to powers that did not forget.",
        "they had seen enough to doubt happy endings, yet still reached for one.",
        "they had learned to sleep light and wake ready.",
        "they had learned which oaths could be bent without breaking.",
        "they had carried a name that fit like borrowed armor.",
        "they had followed a star, a song, or a scream—perhaps all three.",
        "they had been told they were too ordinary until the road disagreed.",
        "they had sharpened kindness until it could cut clean as steel.",
        "they had buried faces they missed more than they admitted.",
        "they had learned to read palms and weather with equal suspicion.",
        "they had traded horse for boat and pride for speed.",
        "they had mapped nightmares until a route appeared in daylight.",
        "they had kept faith like a coal blown gently bright again.",
        "they had learned that silence could be shelter or bait.",
        "they had chased echoes until one introduced itself as memory.",
        "they had stitched pride back into their voice after humiliation.",
        "they had memorized roads by the sound of gravel under boots.",
        "they had refused a throne and inherited its shadows anyway.",
        "they had learned to laugh where laughter was a kind of shield.",
        "they had studied birds until flight seemed like honesty.",
        "they had carried water for strangers until kindness became habit.",
        "they had measured time by how many doors still scared them.",
        "they had learned to bargain without selling the parts worth saving.",
        "they had followed smoke to fires that warmed and fires that judged.",
        "they had practiced mercy until it looked like strategy.",
        "they had learned to kneel without surrendering spine.",
        "they had stolen only what shame later called necessity.",
        "they had kept a list of names they intended to outlive.",
        "they had learned to sing low so enemies underestimated range.",
        "they had mistaken luck for virtue once and paid tuition.",
        "they had braided rosemary into cloaks to calm their own breath.",
        "they had learned which wells held gossip and which held water.",
        "they had sharpened questions until answers arrived bruised.",
        "they had mistaken tenderness for trap and trap for tenderness.",
        "they had followed ship lights until shore became negotiable.",
        "they had taught their hands to remember gentleness after war.",
        "they had learned to read a crowd like a weather front.",
        "they had buried coins for travelers they would never meet.",
        "they had practiced walking away until it stopped looking like cowardice.",
        "they had learned to pray in verbs instead of promises.",
        "they had mistaken hunger for destiny until bread corrected them.",
        "they had followed footprints that told two stories at once.",
        "they had learned that every exile invents a hometown.",
        "they had carried someone else's hope until it fit their hands.",
        "they had learned to close doors so softly fear missed the click.",
    ]
    write_json("descriptions.json", [w(s) for s in desc])

    def merge_weighted(path, additions):
        p = os.path.join(ROOT, path)
        with open(p, "r", encoding="utf-8") as f:
            cur = json.load(f)
        seen = {tuple(x.get("expansion", [])) for x in cur}
        for item in additions:
            t = tuple(item.get("expansion", []))
            if t not in seen:
                seen.add(t)
                cur.append(item)
        with open(p, "w", encoding="utf-8") as f:
            json.dump(cur, f, indent=2, ensure_ascii=False)
        print("merged", path, "total", len(cur))

    merge_weighted(
        "characters.json",
        [w(s, 2) for s in [
            "a cartographer who charted regions that shift overnight",
            "a beekeeper whose hives distill rumors into honey",
            "a rope dancer who negotiates treaties midair",
            "a forensic chef who reads crimes in kitchen dust",
            "a sigil lawyer who argues contracts with spirits",
            "a tide accountant who balances harbors like ledgers",
            "a lantern mender who repairs broken moons",
            "a storm chaperone who escorts disasters politely out",
            "a bookbinder who sews vanished chapters back into spines",
            "a meteor shepherd who herds shooting stars away from cities",
            "a rust prophet who translates corrosion into timelines",
            "a violin duelist who wins fights in quarter notes",
            "a cloud tailor who stitches thunder into linings",
            "a memory notary who stamps recollections as legal tender",
            "a moss diplomat who speaks slowly and wins slowly",
            "a glassblower who traps echoes inside paperweights",
            "a dust knight who fights allergies like dragons",
            "a starlit paramedic who bandages constellations",
            "a rumor cartographer who maps whispers street by street",
            "a rain broker who sells showers on installment",
            "a ink river guide who ferries letters upstream",
            "a bone architect who remodels skeletons for endurance",
            "a shadow veterinarian who treats silhouettes for lameness",
            "a oath mechanic who tunes promises until they hum true",
            "a midnight baker whose bread reveals tomorrow's weather",
            "a fossil clown who makes extinct audiences laugh anyway",
            "a wind notary who notarizes gusts",
            "a grief engineer who builds bridges from tears",
            "a spice inquisitor who interrogates pepper until it confesses",
            "a horizon launderer who bleaches sunsets back to innocence",
            "a flute assassin whose notes cut purse strings only",
            "a marble tutor who teaches statues to blink once",
            "a thunder therapist who listens to storms without interrupting",
            "a parchment lifeguard who pulls swimmers from archives",
            "a velvet blacksmith who hammers softness into armor",
            "a compass therapist who reorients lost guilt",
            "a snow attorney who defends flakes against accusations",
            "a moth librarian who catalogs holes in knowledge",
            "a vinegar sage who pickles prophecies for winter",
            "a hourglass banker who loans minutes at cruel interest",
            "a quilt general who mobilizes patches into formation",
            "a root whisperer who translates vegetables' grievances",
            "a soap historian who washes sins out of chronicles",
            "a chandelier medic who resets lights' heartbeats",
            "a gravel poet who writes epics in crunch patterns",
            "a chalk sentinel who redraws borders when bullies nap",
            "a fog banker who invests in visibility futures",
            "a feather blacksmith who forges quills that debate back",
        ]]
        + [w("a wandering judge who weighs hearts with honest thumbs", 1)]
        + [w("a tea oracle who reads leaves like litigation", 1)]
        + [w("a sand pilot who navigates dunes by taste", 1)]
        + [w("a choir spy who steals secrets in harmony", 1)]
        + [w("a bridge therapist who counsels planks through anxiety", 1)]
        + [w("a candle scientist who measures darkness in wax grams", 1)]
        + [w("a map eater who digests borders to calm nations", 1)]
        + [w("a ribbon general who ties armies into bows", 1)]
        + [w("a hail negotiator who bargains with sky for crops", 1)]
        + [w("a root doctor who prescribes soil walks", 1)]
        + [w("a mirror coach who trains reflections to flinch less", 1)]
        + [w("a flour witch who kneads futures into dough", 1)]
        + [w("a gravel ambassador who speaks only in crunch dialects", 1)]
        + [w("a ink detective who follows stains like breadcrumbs", 1)]
        + [w("a cloud notary who stamps cumulus with approvals", 1)]
        + [w("a bone librarian who shelves marrow like manuscripts", 1)]
        + [w("a storm accountant who audits lightning losses", 1)]
        + [w("a velvet geologist who studies softness under pressure", 1)]
        + [w("a moth diplomat who trades wingdust for truces", 1)]
        + [w("a vinegar knight who seasons courage sour and strong", 1)]
        + [w("a snow historian who preserves avalanches in jars", 1)]
        + [w("a ribbon engineer who suspends bridges from silk", 1)]
        + [w("a hourglass medic who performs triage on wasted time", 1)]
        + [w("a frost lawyer who defends icicles in spring court", 1)]
        + [w("a thunder cartographer who maps sound before light", 1)]
        + [w("a chalk witch who hexes arrogance into equations", 1)]
        + [w("a root assassin who ends tyrants via tripped thresholds", 1)]
        + [w("a soap paladin who washes corruption without drama", 1)]
        + [w("a chandelier thief who steals only ugly light", 1)]
        + [w("a gravel monk who prays in percussive rosaries", 1)]
        + [w("a fog notary who witnesses disappearances legally", 1)]
        + [w("a feather scholar who indexes plumes like evidence", 1)]
        + [w("a bone sailor who navigates reefs by listening to calcium", 1)]
        + [w("a spice paladin who defends bland towns from mediocrity", 1)]
        + [w("a horizon thief who steals sunsets for the colorblind", 1)]
        + [w("a flute cartographer who maps valleys by echo returns", 1)]
        + [w("a marble witch who animates statues only during eclipses", 1)]
        + [w("a thunder baker who kneads storms into sourdough", 1)]
        + [w("a parchment pilot who sails contracts through bureaucratic fog", 1)]
        + [w("a velvet assassin who silences arrogance with a shush", 1)]
        + [w("a compass witch who spins needles until truth dizzy falls out", 1)]
        + [w("a snow broker who sells silence by the drift", 1)]
        + [w("a moth paramedic who rescues flames from light addiction", 1)]
    )

    merge_weighted(
        "locations.json",
        [w(s) for s in [
            "along the ridgeline where lightning rehearses speeches,",
            "inside a bankrupt observatory full of honest stars,",
            "near the pier where knots learn to untie themselves,",
            "between two kingdoms scheduled for mutual forgetting,",
            "at the mouth of a canyon that hums in thirds,",
            "in a salt flat where mirrors argue with the sun,",
            "within a greenhouse of carnivorous orchids,",
            "on a tram line suspended over a city of smoke,",
            "beside a river dyed indigo for treaty-signing week,",
            "under a tree whose roots transcribe confessions,",
            "in a ward where sleep is rationed by polite clerks,",
            "at the lip of a crater filled with polite rain,",
            "inside a vault built to store unfinished songs,",
            "on a glacier that grants wishes only in celsius,",
            "near a bridge toll paid in memories, not coin,",
            "in a district zoned for duels at dawn and diplomacy at lunch,",
            "within a market where every stall sells alibis,",
            "at the edge of a map where cartographers wept,",
            "inside a bathhouse heated by dragon payroll,",
            "on a cliff where winds draft legal complaints,",
            "in a fen where fireflies spell out warnings,",
            "within a scriptorium that corrects authors overnight,",
            "at the center of a maze replanted each season,",
            "near a lighthouse built inverted into the seabed,",
            "inside a granary that measures harvests in whispers,",
        ]]
    )

    merge_weighted(
        "conflicts.json",
        [w(s) for s in [
            "the tide of evidence turned without warning",
            "their signature became a weapon someone else wielded",
            "a vow spoken aloud refused to stay metaphorical",
            "the ground remembered crimes the courts forgot",
            "a treaty candle burned backward through clauses",
            "their reflection began arriving late to mirrors",
            "an heirloom map revealed doors in people, not walls",
            "the city bell rang a frequency only traitors heard",
            "a plague of truthfulness made politics impossible",
            "their shadow filed for independent citizenship",
            "a river reversed and demanded tolls upstream",
            "the stars aligned into an insult nobody could unsee",
            "a choir began singing verdicts instead of hymns",
            "every bridge they crossed billed them in years",
            "their blood type changed to match a stranger's claim",
            "a courtroom statue stepped down to testify",
            "the harvest failed because the soil wanted an apology first",
            "their dreams started cc'ing the enemy by accident",
            "a comet wrote their name and then struck through it",
            "every lock in the city learned their key by heart",
            "a peace festival ended with two competing wars",
            "their voice echoed before they spoke, accusing early",
            "the archives caught fire with selective politeness",
            "a bargain signed in wine revealed teeth in the morning",
            "the crown melted only on honest brows",
        ]]
    )

    merge_weighted(
        "resolutions.json",
        [w(s) for s in [
            "the debt was paid in work that outlasted shame",
            "the city learned to govern without needing monsters",
            "they accepted exile if it meant the truth stayed fed",
            "the villain's name became a synonym for caution, not glory",
            "peace arrived as routine, boring and therefore real",
            "the artifact was buried where ambition rusts fastest",
            "they traded fame for a harbor that remembered them kindly",
            "the war ended when both sides ran out of stories",
            "a garden grew from ashes without needing metaphor",
            "they chose repair over victory and won anyway",
            "the prophecy retired and took up beekeeping",
            "the curse became a teacher nobody thanked aloud",
            "they returned keys they never should have held",
            "the throne stood empty and the maps looked healthier",
            "a bridge opened that charged only in patience",
            "the truth was smaller than fear but heavier to carry",
            "they forgave slowly, the way metal forgives rust",
            "the storm passed because someone admitted fault first",
            "a library opened where weapons were catalogued as warnings",
            "they paid villains in the coin of irrelevance",
            "the alliance held because jokes were finally shared",
            "the hero's statue blinked once, approvingly",
            "the land healed where footsteps slowed to listen",
            "they traded crowns for cloaks and kept both blood cold",
            "the song ended and instruments stayed wisely silent",
        ]]
    )

    merge_weighted(
        "epilogues.json",
        [w(s) for s in [
            " Carpenters measured peace in boards that did not splinter.",
            " River traders waved, no longer checking for pirates first.",
            " The market learned a new joke and let it circulate free.",
            " Schoolrooms quoted their cautionary kindness for decades.",
            " The harbor gulls grew fat on honest crumbs.",
            " Maps were redrawn with fewer teeth on the borders.",
            " The tavern fireplace stopped crackling like a verdict.",
            " Festival lights stayed lit an extra hour for strangers.",
            " A well was dug where old lies had been buried shallow.",
            " The bell tower learned to ring without trembling.",
            " Dogs slept in doorways without flinching at boots.",
            " Nurses told the story to calm fevers, not egos.",
            " Farmers planted borders with flowers instead of spikes.",
            " The courthouse steps gentled under slower feet.",
            " Lovers danced where duels had scheduled themselves.",
        ]]
    )

    with open(os.path.join(ROOT, "names.json"), "r", encoding="utf-8") as f:
        names = json.load(f)
    extra_names = [
        "Aldwin", "Beryn", "Calyx", "Drystan", "Eirwen", "Faolan", "Giselle", "Hadrien",
        "Iskander", "Jocelyn", "Kerensa", "Lareth", "Melisende", "Niall", "Oriana", "Perrin",
        "Quinlan", "Romilly", "Seren", "Torin", "Una", "Vesna", "Wallis", "Xander", "Yseult",
        "Zephyrine", "Anwen", "Bronte", "Cador", "Deryn", "Eulalia", "Fendrel", "Gwyneth",
        "Haldor", "Idris", "Jareth", "Katell", "Lorcan", "Mireya", "Nerys", "Owyn", "Pryderi",
        "Rhoswen", "Selene", "Taran", "Urien", "Vevina", "Winifred", "Xavia", "Yorick", "Zoraida",
        "Ailis", "Branoc", "Catrin", "Dwyn", "Efnisien", "Faelan", "Gorlois", "Heulwen", "Ivor",
        "Jenara", "Kian", "Linnet", "Morcant", "Niam", "Orwen", "Prydain", "Rhian", "Sioned",
        "Talfryn", "Uriana", "Vaughn", "Wynfor", "Xiomara", "Yestin", "Zennor", "Aeron", "Briallen",
        "Cairbre", "Dellan", "Evanthe", "Finian", "Gwalchmai", "Hedra", "Iolanthe", "Jowan",
        "Keira", "Llwyd", "Maelor", "Nisien", "Orlaith", "Padrig", "Ruan", "Searlait", "Telyn",
        "Uther", "Vanya", "Wynne", "Xabat", "Ygraine", "Zephan", "Annis", "Belenos", "Cai",
        "Donwen", "Elidyr", "Ffion", "Geraint", "Hafren", "Idelle", "Jory", "Kenver", "Lowenna",
        "Mabon", "Nerina", "Odran", "Prydwen", "Rhonwen", "Sayer", "Teleri", "Ulfius", "Vortigern",
        "Wenna", "Xanthea", "Ynyr", "Zephyra",
    ]
    seen_n = set(names)
    for n in extra_names:
        if n not in seen_n:
            seen_n.add(n)
            names.append(n)
    while len(names) < 220:
        names.append(f"Name{len(names)}")
    write_json("names.json", names[: max(220, len(names))])


if __name__ == "__main__":
    main()
